# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddBrotherWindow.ui'
#
# Created: Sun Nov 16 20:08:00 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AddBrotherWindow(object):
    def setupUi(self, AddBrotherWindow):
        AddBrotherWindow.setObjectName("AddBrotherWindow")
        AddBrotherWindow.resize(391, 338)
        self.gridLayout_2 = QtGui.QGridLayout(AddBrotherWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtGui.QFrame(AddBrotherWindow)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.frame_7)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.line_f_name = QtGui.QLineEdit(self.frame_2)
        self.line_f_name.setObjectName("line_f_name")
        self.gridLayout.addWidget(self.line_f_name, 0, 1, 1, 1)
        self.line_m_name = QtGui.QLineEdit(self.frame_2)
        self.line_m_name.setObjectName("line_m_name")
        self.gridLayout.addWidget(self.line_m_name, 3, 1, 1, 1)
        self.line_l_name = QtGui.QLineEdit(self.frame_2)
        self.line_l_name.setObjectName("line_l_name")
        self.gridLayout.addWidget(self.line_l_name, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_phone = QtGui.QLineEdit(self.frame_3)
        self.line_phone.setObjectName("line_phone")
        self.gridLayout_4.addWidget(self.line_phone, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.line_email = QtGui.QLineEdit(self.frame_3)
        self.line_email.setObjectName("line_email")
        self.gridLayout_4.addWidget(self.line_email, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_6 = QtGui.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.combo_congregation = QtGui.QComboBox(self.frame_4)
        self.combo_congregation.setObjectName("combo_congregation")
        self.combo_congregation.addItem("")
        self.combo_congregation.addItem("")
        self.combo_congregation.addItem("")
        self.gridLayout_8.addWidget(self.combo_congregation, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 0, 1, 1)
        self.combo_publisher = QtGui.QComboBox(self.frame_4)
        self.combo_publisher.setObjectName("combo_publisher")
        self.combo_publisher.addItem("")
        self.combo_publisher.addItem("")
        self.combo_publisher.addItem("")
        self.gridLayout_8.addWidget(self.combo_publisher, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 3)
        self.check_chairman = QtGui.QCheckBox(self.frame_5)
        self.check_chairman.setObjectName("check_chairman")
        self.gridLayout_9.addWidget(self.check_chairman, 1, 0, 1, 1)
        self.check_speaker = QtGui.QCheckBox(self.frame_5)
        self.check_speaker.setObjectName("check_speaker")
        self.gridLayout_9.addWidget(self.check_speaker, 1, 1, 1, 1)
        self.check_talkC = QtGui.QCheckBox(self.frame_5)
        self.check_talkC.setObjectName("check_talkC")
        self.gridLayout_9.addWidget(self.check_talkC, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtGui.QFrame(self.tab_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.text_note = QtGui.QTextEdit(self.frame_6)
        self.text_note.setObjectName("text_note")
        self.gridLayout_6.addWidget(self.text_note, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(AddBrotherWindow)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_4 = QtGui.QCheckBox(self.frame)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_close = QtGui.QPushButton(self.frame)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.button_add = QtGui.QPushButton(self.frame)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(AddBrotherWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), AddBrotherWindow.close)
        QtCore.QMetaObject.connectSlotsByName(AddBrotherWindow)
        AddBrotherWindow.setTabOrder(self.tabWidget, self.line_f_name)
        AddBrotherWindow.setTabOrder(self.line_f_name, self.line_m_name)
        AddBrotherWindow.setTabOrder(self.line_m_name, self.line_l_name)
        AddBrotherWindow.setTabOrder(self.line_l_name, self.line_phone)
        AddBrotherWindow.setTabOrder(self.line_phone, self.line_email)
        AddBrotherWindow.setTabOrder(self.line_email, self.combo_congregation)
        AddBrotherWindow.setTabOrder(self.combo_congregation, self.combo_publisher)
        AddBrotherWindow.setTabOrder(self.combo_publisher, self.check_chairman)
        AddBrotherWindow.setTabOrder(self.check_chairman, self.check_speaker)
        AddBrotherWindow.setTabOrder(self.check_speaker, self.check_talkC)
        AddBrotherWindow.setTabOrder(self.check_talkC, self.text_note)
        AddBrotherWindow.setTabOrder(self.text_note, self.button_close)
        AddBrotherWindow.setTabOrder(self.button_close, self.button_add)

    def retranslateUi(self, AddBrotherWindow):
        AddBrotherWindow.setWindowTitle(QtGui.QApplication.translate("AddBrotherWindow", "Add Brother", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AddBrotherWindow", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddBrotherWindow", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddBrotherWindow", "Middle Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AddBrotherWindow", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AddBrotherWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("AddBrotherWindow", "Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AddBrotherWindow", "Congregation", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_congregation.setItemText(0, QtGui.QApplication.translate("AddBrotherWindow", "Cong 1", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_congregation.setItemText(1, QtGui.QApplication.translate("AddBrotherWindow", "Cong 2", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_congregation.setItemText(2, QtGui.QApplication.translate("AddBrotherWindow", "Cong 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AddBrotherWindow", "Responsibility", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_publisher.setItemText(0, QtGui.QApplication.translate("AddBrotherWindow", "Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_publisher.setItemText(1, QtGui.QApplication.translate("AddBrotherWindow", "Ministerial Servant", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_publisher.setItemText(2, QtGui.QApplication.translate("AddBrotherWindow", "Elder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AddBrotherWindow", "Serves in the following capacity:", None, QtGui.QApplication.UnicodeUTF8))
        self.check_chairman.setText(QtGui.QApplication.translate("AddBrotherWindow", "Chairman", None, QtGui.QApplication.UnicodeUTF8))
        self.check_speaker.setText(QtGui.QApplication.translate("AddBrotherWindow", "Speaker", None, QtGui.QApplication.UnicodeUTF8))
        self.check_talkC.setText(QtGui.QApplication.translate("AddBrotherWindow", "Talk Coordinator", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("AddBrotherWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("AddBrotherWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("AddBrotherWindow", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.button_close.setText(QtGui.QApplication.translate("AddBrotherWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setText(QtGui.QApplication.translate("AddBrotherWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))

