# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/MainWindow.ui'
#
# Created: Tue Nov 18 11:55:10 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 289)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.table_upcoming_talks = QtGui.QTableWidget(self.tab)
        self.table_upcoming_talks.setObjectName("table_upcoming_talks")
        self.table_upcoming_talks.setColumnCount(0)
        self.table_upcoming_talks.setRowCount(0)
        self.gridLayout.addWidget(self.table_upcoming_talks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(43, 43))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDatabase = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainWindow/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabase.setIcon(icon)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionBrothers = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MainWindow/system-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrothers.setIcon(icon1)
        self.actionBrothers.setObjectName("actionBrothers")
        self.actionReports = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MainWindow/x-office-presentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReports.setIcon(icon2)
        self.actionReports.setObjectName("actionReports")
        self.actionSettings = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MainWindow/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCongregation = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/MainWindow/go-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCongregation.setIcon(icon4)
        self.actionCongregation.setObjectName("actionCongregation")
        self.actionExit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/MainWindow/system-log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionDatabase)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBrothers)
        self.toolBar.addAction(self.actionCongregation)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReports)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyTalkManager", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Upcoming talks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Incoming speakers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Outgoing speakers", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabase.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabase.setToolTip(QtGui.QApplication.translate("MainWindow", "Tools relating to the database.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrothers.setText(QtGui.QApplication.translate("MainWindow", "Brothers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrothers.setToolTip(QtGui.QApplication.translate("MainWindow", "List of brothers to use.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReports.setText(QtGui.QApplication.translate("MainWindow", "Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReports.setToolTip(QtGui.QApplication.translate("MainWindow", "Produce reports.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Settings for pyTalkManager.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCongregation.setText(QtGui.QApplication.translate("MainWindow", "Congregations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCongregation.setToolTip(QtGui.QApplication.translate("MainWindow", "List of congregations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
