# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrotherWindow.ui'
#
# Created: Mon Jan  5 10:35:25 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BrotherWindow(object):
    def setupUi(self, BrotherWindow):
        BrotherWindow.setObjectName("BrotherWindow")
        BrotherWindow.resize(674, 382)
        BrotherWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        BrotherWindow.setAutoFillBackground(True)
        BrotherWindow.setSizeGripEnabled(True)
        BrotherWindow.setModal(False)
        self.gridLayout = QtGui.QGridLayout(BrotherWindow)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtGui.QTableWidget(BrotherWindow)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(BrotherWindow)
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.radio_coord = QtGui.QRadioButton(self.frame_6)
        self.radio_coord.setObjectName("radio_coord")
        self.gridLayout_6.addWidget(self.radio_coord, 5, 0, 1, 1)
        self.radio_ms = QtGui.QRadioButton(self.frame_6)
        self.radio_ms.setObjectName("radio_ms")
        self.gridLayout_6.addWidget(self.radio_ms, 3, 0, 1, 1)
        self.radio_all = QtGui.QRadioButton(self.frame_6)
        self.radio_all.setChecked(True)
        self.radio_all.setObjectName("radio_all")
        self.gridLayout_6.addWidget(self.radio_all, 1, 0, 1, 1)
        self.radio_elder = QtGui.QRadioButton(self.frame_6)
        self.radio_elder.setObjectName("radio_elder")
        self.gridLayout_6.addWidget(self.radio_elder, 1, 1, 1, 1)
        self.radio_pub = QtGui.QRadioButton(self.frame_6)
        self.radio_pub.setObjectName("radio_pub")
        self.gridLayout_6.addWidget(self.radio_pub, 3, 1, 1, 1)
        self.combo_cong = QtGui.QComboBox(self.frame_6)
        self.combo_cong.setObjectName("combo_cong")
        self.gridLayout_6.addWidget(self.combo_cong, 7, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.radio_fname = QtGui.QRadioButton(self.frame_4)
        self.radio_fname.setChecked(True)
        self.radio_fname.setObjectName("radio_fname")
        self.gridLayout_3.addWidget(self.radio_fname, 1, 0, 1, 1)
        self.radio_l_name = QtGui.QRadioButton(self.frame_4)
        self.radio_l_name.setObjectName("radio_l_name")
        self.gridLayout_3.addWidget(self.radio_l_name, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(BrotherWindow)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_close = QtGui.QPushButton(self.frame)
        self.button_close.setObjectName("button_close")
        self.gridLayout_2.addWidget(self.button_close, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(BrotherWindow)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(6, 6, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_delete = QtGui.QPushButton(self.frame_2)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.button_add = QtGui.QPushButton(self.frame_2)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_edit = QtGui.QPushButton(self.frame_2)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(BrotherWindow)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), BrotherWindow.close)
        QtCore.QMetaObject.connectSlotsByName(BrotherWindow)

    def retranslateUi(self, BrotherWindow):
        BrotherWindow.setWindowTitle(QtGui.QApplication.translate("BrotherWindow", "Brothers", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "<html><head/><body><p>An orderd list of all the brothers entered into the database. Names are sorted first by <span style=\" font-style:italic;\">first</span> or <span style=\" font-style:italic;\">last</span> name and then by their congregation.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("BrotherWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("BrotherWindow", "Congregation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BrotherWindow", "From:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BrotherWindow", "Display:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_coord.setText(QtGui.QApplication.translate("BrotherWindow", "Talk Coordinators", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_ms.setText(QtGui.QApplication.translate("BrotherWindow", "Ministial Servents", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_all.setText(QtGui.QApplication.translate("BrotherWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_elder.setText(QtGui.QApplication.translate("BrotherWindow", "Elders", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_pub.setText(QtGui.QApplication.translate("BrotherWindow", "Publishers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BrotherWindow", "Sort by:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fname.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "Sort the brother list by first names.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fname.setText(QtGui.QApplication.translate("BrotherWindow", "First name", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_l_name.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "Sort the brother list by last names.", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_l_name.setText(QtGui.QApplication.translate("BrotherWindow", "Last name", None, QtGui.QApplication.UnicodeUTF8))
        self.button_close.setText(QtGui.QApplication.translate("BrotherWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.button_delete.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "Remove a brother from the list.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_delete.setText(QtGui.QApplication.translate("BrotherWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "Add a brother to the list.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setText(QtGui.QApplication.translate("BrotherWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.button_edit.setWhatsThis(QtGui.QApplication.translate("BrotherWindow", "Edit a brother\'s information.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_edit.setText(QtGui.QApplication.translate("BrotherWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))

